package learn.atliens.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "categories")
public class Category {

    //  - categoryId int primary key auto_increment,
    //  - `name` varchar(50) not null unique
    //  - isExplicit boolean not null

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String categoryId;

    @DynamoDBAttribute
    private String name;

//    @DynamoDBAttribute
//    private boolean isExplicit;
}
