package learn.atliens.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

//word_id int primary key auto_increment,
//name varchar(1000) not null (doesn’t have to be unique)
//definition varchar(2048) not null
//example varchar (2048) not null
//video_url varchar(2048) (optional)
//use_rating int(5) not null (limit number 1 to 5)

@Data
@DynamoDBTable(tableName = "words")
public class Word {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String wordId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String definition;

    @DynamoDBAttribute
    private String example;

    @DynamoDBAttribute
    private String videoUrl;

    @DynamoDBAttribute
    private String useRating;

    @DynamoDBAttribute
    private String category1Id;

    @DynamoDBAttribute
    private String category2Id;

    @DynamoDBAttribute
    private String category3Id;


//    public Word() {
//    }
//
//    public Word(int wordId, String name, String definition, String example, String videoUrl, int useRating, int category1Id, int category2Id, int category3Id) {
//        this.wordId = wordId;
//        this.name = name;
//        this.definition = definition;
//        this.example = example;
//        this.videoUrl = videoUrl;
//        this.useRating = useRating;
//        this.category1Id = category1Id;
//        this.category2Id = category2Id;
//        this.category3Id = category3Id;
//    }
//
//    public int getWordId() {
//        return wordId;
//    }
//
//    public void setWordId(int wordId) {
//        this.wordId = wordId;
//    }
//
//    public String getName() {
//        return name;
//    }
//
//    public void setName(String name) {
//        this.name = name;
//    }
//
//    public String getDefinition() {
//        return definition;
//    }
//
//    public void setDefinition(String definition) {
//        this.definition = definition;
//    }
//
//    public String getExample() {
//        return example;
//    }
//
//    public void setExample(String example) {
//        this.example = example;
//    }
//
//    public String getVideoUrl() {
//        return videoUrl;
//    }
//
//    public void setVideoUrl(String videoUrl) {
//        this.videoUrl = videoUrl;
//    }
//
//    public int getUseRating() {
//        return useRating;
//    }
//
//    public void setUseRating(int useRating) {
//        this.useRating = useRating;
//    }
//
//    public int getCategory1Id() {
//        return category1Id;
//    }
//
//    public void setCategory1Id(int category1Id) {
//        this.category1Id = category1Id;
//    }
//
//    public int getCategory2Id() {
//        return category2Id;
//    }
//
//    public void setCategory2Id(int category2Id) {
//        this.category2Id = category2Id;
//    }
//
//    public int getCategory3Id() {
//        return category3Id;
//    }
//
//    public void setCategory3Id(int category3Id) {
//        this.category3Id = category3Id;
//    }
//
//    @Override
//    public String toString() {
//        return "Word{" +
//                "wordId=" + wordId +
//                ", name='" + name + '\'' +
//                ", definition='" + definition + '\'' +
//                ", example='" + example + '\'' +
//                ", videoUrl='" + videoUrl + '\'' +
//                ", useRating=" + useRating +
//                ", category1Id=" + category1Id +
//                ", category2Id=" + category2Id +
//                ", category3Id=" + category3Id +
//                '}';
//    }


}
