package learn.atliens.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

//word_id int primary key auto_increment,
//name varchar(1000) not null (doesn’t have to be unique)
//definition varchar(2048) not null
//example varchar (2048) not null
//video_url varchar(2048) (optional)
//use_rating int(5) not null (limit number 1 to 5)

@Data
@DynamoDBTable(tableName = "words")
public class Word {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String wordId;

    @DynamoDBIndexHashKey (globalSecondaryIndexName = "name-useRating-index")
    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String definition;

    @DynamoDBAttribute
    private String example;

    @DynamoDBAttribute
    private String videoUrl;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "name-useRating-index")
    @DynamoDBAttribute
    private int useRating;

    // TODO: lookup if we can add categories list instead of 1,2,3
    @DynamoDBAttribute
    private String category1Id;

    @DynamoDBAttribute
    private String category2Id;

    @DynamoDBAttribute
    private String category3Id;

    // TODO: add explicit tag here

}
