@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhdGxpZW5zIiwic3ViIjoiY29keTIiLCJ1c2VyX2lkIjoiYjM3NzFlZGYtOGNhMS00NmJhLWIwMjQtNzU1N2ZhMTUwNTMzIiwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY3NDc1MzY2MH0.V_oYTthB2vnxFVZOSgNjuMxiWCLUAiOwwcpbyOsEpOk

get http://localhost:8080/atliens/user

###

get http://localhost:8080/atliens/user/cody2

###

Post http://localhost:8080/atliens/user/create_account
Content-Type: application/json

{
    "username": "cody5",
    "password": "banks"
}

###

Post http://localhost:8080/atliens/authenticate
Content-Type: application/json

{
    "username": "cody2",
    "password": "banks"
}

###

DELETE http://localhost:8080/atliens/word/40409bac-008f-4e6c-85a4-893066c5f70f HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST http://localhost:8080/atliens/word HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

    {
        "name": "bye",
        "definition": "Test",
        "example": "Test",
        "videoUrl": "Test",
        "useRating": 0,
        "categories": "Happy",
        "explicit": false
    }

###

PUT http://localhost:8080/atliens/word/396f042f-897f-490e-b899-6b7c71004e50 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
         "wordId": "396f042f-897f-490e-b899-6b7c71004e50",
        "name": "Test1",
        "definition": "Testing",
        "example": "Testing",
        "videoUrl": "Testing",
        "useRating": 5,
        "categories": "Sad"
}

